include:
  - compose.frontend.yaml
  - compose.backend.yaml
  - compose.database.yaml
  - compose.wstest.yaml
  - compose.netdata.yaml
  - compose.mongodb.yaml

services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    restart: on-failure
    volumes:
      - type: bind
        source: "./nginx/nginx.conf"
        target: "/etc/nginx/nginx.conf"
        read_only: true
      - type: bind
        source: "./nginx/conf.d"
        target: "/etc/nginx/conf.d"
        read_only: true
      - type: bind
        source: "/etc/letsencrypt/archive"
        target: "/nginx-cert"
        read_only: true
    ports:
      - "80:80"
      - "8080:80"
      - "443:443"
      - "8443:443"
    networks:
      - "frontend-network"
      - "backend-network"
      - "statistics-network"

networks:
  frontend-network:
    driver: bridge

  backend-network:
    driver: bridge

  statistics-network:
    driver: bridge

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
