include:
  - compose.frontend.yaml
  - compose.backend.yaml
  - compose.database.yaml

services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    restart: on-failure
    volumes:
      - type: bind
        source: "./sites-enabled"
        target: "/etc/nginx/conf.d"
        read_only: true
      - type: bind
        source: "/etc/letsencrypt/archive"
        target: "/nginx-cert"
        read_only: true
    ports:
      - "80:80"
      - "8080:80"
      - "443:443"
      - "8443:443"
    networks:
      - "frontend-network"
      - "backend-network"
      - "statistics-network"

  netdata:
    image: netdata/netdata
    container_name: netdata
    pid: host
    network_mode: host
    restart: always
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - "statistics-network"

networks:
  frontend-network:
    driver: bridge

  backend-network:
    driver: bridge

  statistics-network:
    driver: bridge

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
