services:
  mongodb1:
    image: mongo:latest
    container_name: mongodb1
    restart: always
    env_file:
      - ./secrets/mongo.env
    entrypoint:
      - bash
      - -c
      - |
        echo "Modifying permission..."
        chmod 400 /data/replica.key
        chown 999:999 /data/replica.key
        echo "Starting MongoDB..."
        exec docker-entrypoint.sh --config /etc/mongod.conf
    healthcheck:
      test: >
        echo "try {
          rs.status()
        } catch (err) {
          rs.initiate({
            _id: 'rs0',
            members: [
              {_id: 0, host: 'db-easytask.vt.in.th:27017', priority:1},
              {_id: 1, host: 'db-easytask.vt.in.th:27018', priority:0.5},
              {_id: 2, host: 'db-easytask.vt.in.th:27019', priority:0.5}
            ]
          })
        }" | mongosh mongodb://$${MONGO_INITDB_ROOT_USERNAME}:$${MONGO_INITDB_ROOT_PASSWORD}@localhost:27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    networks:
      - "backend-network"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb1_data:/data/db"
      - "mongodb1_config:/data/configdb"
      - "~/deploy/secrets/mongodb.dump:/restore/mongodb.dump"
      - "./mongodb/mongod.conf:/etc/mongod.conf"
      - "~/deploy/secrets/replica.key:/data/replica.key"

  mongodb2:
    image: mongo:latest
    container_name: mongodb2
    restart: always
    env_file:
      - ./secrets/mongo.env
    entrypoint:
      - bash
      - -c
      - |
        echo "Modifying permission..."
        chmod 400 /data/replica.key
        chown 999:999 /data/replica.key
        echo "Starting MongoDB..."
        exec docker-entrypoint.sh --config /etc/mongod.conf
    networks:
      - "backend-network"
    ports:
      - "27018:27017"
    volumes:
      - "mongodb2_data:/data/db"
      - "mongodb2_config:/data/configdb"
      - "~/deploy/secrets/mongodb.dump:/restore/mongodb.dump"
      - "./mongodb/mongod.conf:/etc/mongod.conf"
      - "~/deploy/secrets/replica.key:/data/replica.key"

  mongodb3:
    image: mongo:latest
    container_name: mongodb3
    restart: always
    env_file:
      - ./secrets/mongo.env
    entrypoint:
      - bash
      - -c
      - |
        echo "Modifying permission..."
        chmod 400 /data/replica.key
        chown 999:999 /data/replica.key
        echo "Starting MongoDB..."
        exec docker-entrypoint.sh --config /etc/mongod.conf
    ports:
      - "27019:27017"
    networks:
      - "backend-network"
    volumes:
      - "mongodb3_data:/data/db"
      - "mongodb3_config:/data/configdb"
      - "~/deploy/secrets/mongodb.dump:/restore/mongodb.dump"
      - "./mongodb/mongod.conf:/etc/mongod.conf"
      - "~/deploy/secrets/replica.key:/data/replica.key"

volumes:
  mongodb1_data:
  mongodb2_data:
  mongodb3_data:
  mongodb1_config:
  mongodb2_config:
  mongodb3_config: