services:
  database:
    image: mongo:latest
    container_name: database
    restart: always
    volumes:
      - "/data/db:/data/db"
      - "/data/configdb:/data/configdb"
      - "~/deploy/secrets/mongodb.dump:/restore/mongodb.dump"
    ports:
      - "27017:27017"
    networks:
      - "backend-network"
