services:
  database:
    image: mongo:latest
    container_name: database
    restart: always
    volumes:
      - mongo_data:/data/db
      - "~/deploy/secrets/mongodb.dump:/restore/mongodb.dump"
    ports:
      - "27017:27017"
    networks:
      - "backend-network"

volumes:
  mongo_data:
    external: true
