name: Deploy Frontend using Docker

# Ensure to run one at a time.
concurrency:
  group: ${{ github.workflow }}
on:
  push:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Set production/development aliases
            if [ "${{ github.ref_name }}" = "main" ]; then \
              export NODE_ENV_SHORT="prod"; \
            elif [ "${{ github.ref_name }}" = "develop" ]; then \
              export NODE_ENV_SHORT="dev"; \
            fi
            
            # Go to deploy directory
            cd "/home/${{ secrets.SSH_USERNAME }}/deploy/"
            
            # Git from GitHub
            export REMOTE_URL="${{ github.server_url }}/${{ github.repository }}"
            git init
            git remote -v | grep -w origin && \
            git remote set-url origin ${REMOTE_URL} || \
            git remote add origin ${REMOTE_URL}
            git reset --hard origin/${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            
            # Rebuild from configuration
            docker compose down reverse-proxy
            docker compose up -d reverse-proxy
            
            docker compose down websocket-test
            docker compose up -d websocket-test
            
            docker compose down database
            docker compose up -d database
            
            docker compose down netdata
            docker compose up -d netdata
            
            # Clear the fxxking cache
            docker builder prune -a -f
            docker image prune -a -f
